name: Continuous Integration

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')

    strategy:
      fail-fast: false

      matrix:
        os: [macos, windows, ubuntu]

        build: [Debug, Release]

        folder: [example, test]

    runs-on: ${{ matrix.os }}-latest

    name: ${{ matrix.folder }}-${{ matrix.os }}-${{ matrix.build }}

    steps:
      - uses: actions/checkout@v1

      - uses: friendlyanon/fetch-core-count@v1
        id: cores

      - name: Set compiler ENV variables on Ubuntu
        if: matrix.os == 'ubuntu'
        run: |
          echo "CC=gcc-10" >> $GITHUB_ENV
          echo "CXX=g++-10" >> $GITHUB_ENV

      - name: Configure
        run: cmake -S ${{ matrix.folder }} -B build
          -D CMAKE_BUILD_TYPE=${{ matrix.build }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build }}

      - name: Test
        if: matrix.folder == 'test'
        working-directory: build
        run: ctest --output-on-failure -C ${{ matrix.build }}
